version: '3.7'

services:
    mysql:
        image: mysql
        environment:
            MYSQL_USER: woodpress
            MYSQL_DATABASE: wordpress
        secrets:
            - root_pass
        deploy:
            placement:
                constraints:
                    - node.role==manager
secrets:
   root_pass:
      file: ./mysecretpassword.txt