version: '3.1'

services:
    mysql:
       image: mysql
       environment:
          MYSQL_USER: woodpress
          MYSQL_DATABASE: wordpress
          #MYSQL_ROOT_PASSWORD: root
       secrets:
          - mysql_root_pass
       deploy:
          placement:
              constraints:
                  - node.role==manager